fix: expression parameter strings are now delimited by a comma
rigetti/quil-rs pull request #214
Opened 2023-06-07 18:24 UTC by MarquessV

List of expressions were being printed without a delimmiting comma. This fixes that issue, as well as refactors some related methods to not allocate in Display.

2023-06-12 17:06 UTC, Shadow53 requested changes

2023-06-12 17:06 UTC, Shadow53 commented on quil-rs/src/instruction/mod.rs
> +    Ok(())
This works fine as-is, but stylistically could be written better. My preference is usually

```suggestion
    let mut iter = values.iter();
    
    if let Some(value) = iter.next() {
        write!(f, "{value}")?;
    }
    
    for value in iter {
        write!(f, ", {value}")?;
    }
    
    Ok(())
```

But I'm also okay with

```suggestion
    for (i, value) in values.iter().enumerate() {
        if i != 0 {
            write!(f, ", ")?;
        }
        write!(f, "{value}")?;
    }
    Ok(())
```

2023-06-12 17:06 UTC, Shadow53 commented on quil-rs/src/instruction/mod.rs
> +    write!(f, ")")
If not, see suggestions on `write_comma_separated_list`

2023-06-12 22:38 UTC, MarquessV commented on quil-rs/src/instruction/mod.rs
> +    write!(f, ")")
I think you called out the right tradeoff, and I'm not sure which is best. My initial hesitation with a prefix argument is that all of this is part of the public API, but I think as long as we restrict it, it's not going to be binding. Coming back to this fresh I don't think any of these write methods really belong in the public API. I don't think they are being used outside of the module, and if they are, I think we can revisit what a proper instruction formatting API might look like. 

All that to say, I ultimately went with the prefix argument.

2023-06-13 18:48 UTC, Shadow53 approved these changes
LGTM

2023-06-14 16:38 UTC, merged